# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 08:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('chat_buddies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_message_chat_buddies', to='message.MessageUser')),
                ('user_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_message_usersend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
