# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageuser',
            name='last_active',
            field=models.DateTimeField(null=True),
        ),
    ]
