# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_messageuser_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageuser',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
