# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_messageuser_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageuser',
            name='user',
            field=models.ManyToManyField(related_name='message_messageuser_user', to='user.User'),
        ),
    ]
