# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20170531_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_message_usersend', to='user.User'),
        ),
    ]
