# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_auto_20170520_0237'),
        ('message', '0009_auto_20170531_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_messageuserinfo_frame', to='message.MessageUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_messageuserinfo_user', to='user.User')),
            ],
        ),
    ]
