# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_messageuser_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageuserinfo',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
