# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0012_auto_20170603_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageuser',
            name='users',
        ),
    ]
