# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0013_remove_messageuser_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageuser',
            old_name='user',
            new_name='users',
        ),
    ]
