# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_auto_20170603_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageuserinfo',
            name='fetch',
            field=models.BooleanField(default=True),
        ),
    ]
