# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0015_messageuserinfo_fetch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
