# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0016_remove_message_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageuser',
            name='read',
        ),
    ]
