# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_auto_20170520_0237'),
        ('message', '0017_remove_messageuser_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('fetch', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_messagereadinfo_message', to='message.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_messagereadinfo_user', to='user.User')),
            ],
        ),
    ]
