# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_networkaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkaccount',
            name='profile_piture',
        ),
        migrations.RemoveField(
            model_name='networkaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='NetworkAccount',
        ),
    ]
