# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_auto_20170520_0237'),
        ('account', '0004_auto_20170608_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_members', models.ManyToManyField(related_name='account_familyfollow_family_members', to='user.User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_familyfollow_user', to='user.User')),
            ],
        ),
    ]
