# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_auto_20170520_0237'),
        ('account', '0005_familyfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('follow_id', models.IntegerField()),
                ('members', models.ManyToManyField(related_name='account_followtimeline_members', to='user.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_followtimeline_user', to='user.User')),
            ],
        ),
    ]
