# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_followtimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followtimeline',
            name='follow_id',
            field=models.IntegerField(unique=True),
        ),
    ]
