# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170622_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyfollow',
            name='family_members',
        ),
        migrations.RemoveField(
            model_name='familyfollow',
            name='user',
        ),
        migrations.DeleteModel(
            name='FamilyFollow',
        ),
    ]
