# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=50)),
                ('target_des', models.TextField()),
                ('content', models.TextField()),
                ('prize', models.TextField()),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('timezone', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
