# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_remove_scholarship_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='target',
            field=models.ManyToManyField(to='scholarship.ScholarshipTarget'),
        ),
    ]
