# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_scholarship_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='prize',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='target_des',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='time_begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='timezone',
            field=models.IntegerField(null=True),
        ),
    ]
