# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_auto_20161202_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='head',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
