# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
