# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='share',
            new_name='is_hour',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_share',
            field=models.BooleanField(default=False),
        ),
    ]
