# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='act',
            new_name='act_description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='city',
        ),
    ]
