# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20160908_1314'),
        ('activities', '0008_auto_20160908_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.City'),
        ),
    ]
