# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_activity_share'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityEnjoy',
            new_name='ActivityParticipants',
        ),
    ]
