# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20160910_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfriendsinvite',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity'),
        ),
        migrations.AlterField(
            model_name='activityparticipants',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity'),
        ),
    ]
