# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_auto_20160910_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='search_page',
            field=models.BooleanField(default=False),
        ),
    ]
