# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_auto_20160911_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityfriendsinvite',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activityfriendsinvite',
            name='friends',
        ),
        migrations.AddField(
            model_name='activityparticipants',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityparticipants',
            name='participate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityparticipants',
            name='refuse',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ActivityFriendsInvite',
        ),
    ]
