# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_auto_20160913_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='who_share',
            field=models.CharField(choices=[('parti', 'parti'), ('fr', 'friends'), ('frfr', 'friendoffriend'), ('world', 'world')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activitycomment',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
