# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_auto_20160913_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='who_join',
        ),
        migrations.AlterField(
            model_name='activity',
            name='act_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='who_share',
            field=models.CharField(choices=[('1', 'me and invite friends'), ('2', 'me, friends'), ('3', 'me, friends and allow friends to enjoy'), ('4', 'me, friends, world and allow friends to enjoy'), ('5', 'me , friends, world and allow world to enjoy')], max_length=1, null=True),
        ),
    ]
