# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_activity_city_unicode'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='act_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_code',
            field=models.CharField(choices=[('Sport', (('1', 'swimming'), ('2', 'football'), ('3', 'badminton'), ('4', 'walking'), ('5', ''))), ('Learning', (('100', 'learning'), ('101', 'school'))), ('Party', (('200', 'party'), ('201', 'eat'), ('202', 'date'))), ('None', (('0', 'create by you'),))], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='who_share',
            field=models.CharField(choices=[('1', 'me and invite friends'), ('2', 'me, friends'), ('3', 'me, friends and allow friends to enjoy'), ('4', 'me, friends, world'), ('5', 'me, friends, world and allow friends to enjoy'), ('6', 'me , friends, world and allow world to enjoy')], max_length=1, null=True),
        ),
    ]
