# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_auto_20160918_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityparticipants',
            name='participants',
        ),
    ]
