# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0025_auto_20160918_0929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='who_being_vote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='who_vote',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
