# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0027_auto_20160918_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityparticipants',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='activityparticipants',
            name='participate',
        ),
        migrations.RemoveField(
            model_name='activityparticipants',
            name='refuse',
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='participate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='refuse',
            field=models.BooleanField(default=False),
        ),
    ]
