# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0028_auto_20160918_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='can_vote',
            field=models.BooleanField(default=True),
        ),
    ]
