# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0030_auto_20160918_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='been_vote',
            field=models.BooleanField(default=False),
        ),
    ]
