# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0031_auto_20160918_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('who_being_vote', 'who_vote', 'info')]),
        ),
    ]
