# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0033_activityimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='act_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_code',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_icon',
            field=models.CharField(choices=[('Sport', (('1', 'badminton'), ('2', 'surfing')))], max_length=10, null=True),
        ),
    ]
