# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0035_auto_20160921_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_icon_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activityvote',
            name='icon',
            field=models.CharField(choices=[('Sport', (('1', 'badminton'), ('2', 'surfing')))], max_length=10),
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='icon',
            field=models.CharField(choices=[('Sport', (('1', 'badminton'), ('2', 'surfing')))], max_length=10, null=True),
        ),
    ]
