# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0036_auto_20160921_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_icon',
        ),
        migrations.RemoveField(
            model_name='activityvote',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='moreinfo',
            name='icon',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_icon_number',
            field=models.CharField(choices=[('Sport', (('1', 'flaticon active person'), ('2', 'flaticon badminton'), ('3', 'flaticon ride bike'), ('4', 'flaticon climbing'), ('5', 'flaticon go fishing'), ('6', 'flaticon golf'), ('7', 'flaticon horse riding'), ('8', 'flaticon flying a kite'), ('9', 'flaticon canoe'), ('10', 'flaticon swimming'), ('11', 'flaticon camping'), ('12', 'flaticon running'), ('13', 'flaticon skateboard'), ('14', 'flaticon ski-lift'), ('15', 'flaticon surfer'), ('16', 'flaticon walking')))], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='activityvote',
            name='icon_number',
            field=models.CharField(choices=[('Sport', (('1', 'flaticon active person'), ('2', 'flaticon badminton'), ('3', 'flaticon ride bike'), ('4', 'flaticon climbing'), ('5', 'flaticon go fishing'), ('6', 'flaticon golf'), ('7', 'flaticon horse riding'), ('8', 'flaticon flying a kite'), ('9', 'flaticon canoe'), ('10', 'flaticon swimming'), ('11', 'flaticon camping'), ('12', 'flaticon running'), ('13', 'flaticon skateboard'), ('14', 'flaticon ski-lift'), ('15', 'flaticon surfer'), ('16', 'flaticon walking')))], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='icon_number',
            field=models.CharField(choices=[('Sport', (('1', 'flaticon active person'), ('2', 'flaticon badminton'), ('3', 'flaticon ride bike'), ('4', 'flaticon climbing'), ('5', 'flaticon go fishing'), ('6', 'flaticon golf'), ('7', 'flaticon horse riding'), ('8', 'flaticon flying a kite'), ('9', 'flaticon canoe'), ('10', 'flaticon swimming'), ('11', 'flaticon camping'), ('12', 'flaticon running'), ('13', 'flaticon skateboard'), ('14', 'flaticon ski-lift'), ('15', 'flaticon surfer'), ('16', 'flaticon walking')))], max_length=10, null=True),
        ),
    ]
