# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0038_auto_20160923_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='vote',
        ),
        migrations.AddField(
            model_name='activityvote',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
