# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0040_auto_20160924_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
