# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0042_auto_20161030_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='who_share',
            new_name='share',
        ),
    ]
