# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0047_auto_20161030_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='rank_name',
            new_name='rank_des',
        ),
        migrations.RenameField(
            model_name='activityvote',
            old_name='vote_name',
            new_name='vote_des',
        ),
    ]
