# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0048_auto_20161030_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='rank_icon_number',
            new_name='rank_icon_code',
        ),
    ]
