# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0049_auto_20161031_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_icon_number',
            new_name='activity_icon_code',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_icon_description',
            new_name='activity_icon_name',
        ),
    ]
