# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0050_auto_20161031_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='timezone',
            field=models.IntegerField(null=True),
        ),
    ]
