# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0051_activity_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityimage',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
