# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20160908_1314'),
        ('activities', '0052_activityimage_is_temporary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImageSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=200, null=True)),
                ('time', models.DateTimeField()),
                ('place', models.CharField(max_length=50, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.City')),
            ],
        ),
        migrations.AddField(
            model_name='activityimageseries',
            name='activityseries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.ActivitySeries'),
        ),
    ]
