# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0053_auto_20161114_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityseries',
            name='city',
        ),
        migrations.AlterField(
            model_name='activityseries',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
