# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0054_auto_20161127_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityimageseries',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activityimageseries',
            name='activityseries',
        ),
        migrations.AddField(
            model_name='activityseries',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.DeleteModel(
            name='ActivityImageSeries',
        ),
    ]
