# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0056_activityseries_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_icon_name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_icon_code',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='search_page',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='street',
        ),
        migrations.AddField(
            model_name='activity',
            name='province',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='province_unicode',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='share',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='activityvote',
            name='vote_icon_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='icon_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
