# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0057_auto_20161222_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='act_description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='time',
        ),
    ]
