# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0058_auto_20161223_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='head',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
