# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('vote', '0003_auto_20170115_1440'),
        ('pro', '0004_auto_20170115_1440'),
        ('activity', '0026_auto_20170115_1336'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0060_remove_activity_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitiesPostFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('activitiespost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_activitiespostfriend_activitiespost', to='activities.ActivitiesPost')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_activitiespostfriend_friend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activitycomment',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activitycomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activityimage',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activityimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activityparticipants',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activityparticipants',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='activityseries',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activityseries',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activityvote',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='moreinfo',
            name='activityparticipants',
        ),
        migrations.RemoveField(
            model_name='moreinfo',
            name='person',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='info',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='who_being_vote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='who_vote',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ActivityComment',
        ),
        migrations.DeleteModel(
            name='ActivityImage',
        ),
        migrations.DeleteModel(
            name='ActivityParticipants',
        ),
        migrations.DeleteModel(
            name='ActivitySeries',
        ),
        migrations.DeleteModel(
            name='ActivityVote',
        ),
        migrations.DeleteModel(
            name='MoreInfo',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='activitiespost',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_activitiespost_activity', to='activity.Activity'),
        ),
        migrations.AddField(
            model_name='activitiespost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_activitiespost_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
