# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 07:52
from __future__ import unicode_literals

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0061_auto_20170115_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiespost',
            name='image',
            field=models.ImageField(null=True, upload_to=activities.models.activitiespost_image_upload),
        ),
    ]
