# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('post', '0001_initial'), ('post', '0002_auto_20170115_0257'), ('post', '0003_postfriend')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('privacy', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_post_user', to=settings.AUTH_USER_MODEL)),
                ('province', models.CharField(max_length=200, null=True)),
                ('province_unicode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_postfriend_friend', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
