# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_auto_20170504_0311'),
        ('post', '0001_squashed_0003_postfriend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='privacy',
        ),
        migrations.RemoveField(
            model_name='post',
            name='province',
        ),
        migrations.RemoveField(
            model_name='post',
            name='province_unicode',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_post_user', to='user.User'),
        ),
        migrations.RemoveField(
            model_name='postfriend',
            name='friend',
        ),
        migrations.AddField(
            model_name='postfriend',
            name='friend',
            field=models.ManyToManyField(related_name='post_postfriend_friend', to='user.User'),
        ),
        migrations.AlterField(
            model_name='postfriend',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_postfriend_post', to='post.Post'),
        ),
    ]
