# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170504_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='old_image',
        ),
    ]
