# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('post', '0003_auto_20170504_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_link_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(related_name='post_post_image', to='files.Image'),
        ),
    ]
