# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20170504_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfriendtag',
            name='friend',
            field=models.ManyToManyField(related_name='post_postfriendtag_friend', to='user.User'),
        ),
        migrations.AlterField(
            model_name='postfriendtag',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_postfriendtag_post', to='post.Post'),
        ),
    ]
