# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 02:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('place', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('timezone', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
