# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-18 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
