# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0004_auto_20161219_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='been_vote',
            field=models.BooleanField(default=False),
        ),
    ]
