# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_grouppost'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='image',
            field=models.ImageField(null=True, upload_to=group.models.upload_image_grouppost),
        ),
    ]
