# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_grouppost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=group.models.upload_group_pic)),
                ('background', models.ImageField(upload_to=group.models.upload_group_pic)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_groupinfo_group', to='group.Group'),
        ),
    ]
