# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20170329_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_groupinfo_group', to='group.Group'),
        ),
    ]
