# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20170330_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
