# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import group.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0009_grouppost_time_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemberDedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_groupmemberdedication_group', to='group.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_groupmemberdedication_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='guess_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='owner_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='background',
            field=models.ImageField(null=True, upload_to=group.models.upload_group_pic),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='image',
            field=models.ImageField(null=True, upload_to=group.models.upload_group_pic),
        ),
    ]
