# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0010_auto_20170331_1659'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupinvitation',
            unique_together=set([('user', 'group')]),
        ),
    ]
