# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_auto_20170401_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='follow',
            field=models.BooleanField(default=True),
        ),
    ]
