# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_groupmember_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvitation',
            name='group_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_groupinvitation_group_member', to='group.GroupMember'),
        ),
        migrations.AddField(
            model_name='groupmemberdedication',
            name='group_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_groupmemberdedication_group_member', to='group.GroupMember'),
        ),
    ]
