# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0002_auto_20160908_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city_code', models.CharField(choices=[('vn-hochiminh', 'Ho Chi Minh'), ('vn-vungtau', 'Vung Tau'), ('vn-hanoi', 'Ha Noi'), ('vn-hue', 'Hue'), ('vn-danang', 'Da Nang'), ('vn-cantho', 'Can Tho')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(choices=[('vn', 'vietnam'), ('us', 'United States of America'), ('uk', 'United Kingdom')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Country'),
        ),
    ]
