# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20160908_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='name_ascii',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='name_ascii',
        ),
        migrations.AddField(
            model_name='city',
            name='name_unicode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_unicode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.CharField(choices=[('vn-hochiminh', 'Ho Chi Minh'), ('vn-vungtau', 'Vung Tau'), ('vn-hanoi', 'Ha Noi'), ('vn-hue', 'Hue'), ('vn-danang', 'Da Nang'), ('vn-cantho', 'Can Tho'), ('vn-haiphong', 'Hai Phong')], max_length=100),
        ),
    ]
