# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20170608_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=50)),
                ('select_goal', models.CharField(max_length=50, null=True)),
                ('introduction', models.TextField()),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.NetworkAccount')),
            ],
        ),
    ]
