# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_networkgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkgoal',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
