# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_networkchatroomtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkChatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_people', models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='networkchatframe',
            name='frame_type',
            field=models.CharField(default='goal', max_length=20),
        ),
        migrations.AddField(
            model_name='networkchatroom',
            name='chat_frame',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='network.NetworkChatFrame'),
        ),
        migrations.AddField(
            model_name='networkchatroom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_networkchatroom_owner', to='network.NetworkAccount'),
        ),
        migrations.AddField(
            model_name='networkchatroom',
            name='tag_topic',
            field=models.ManyToManyField(related_name='network_networkchatroom_tag_topic', to='network.NetworkChatroomTopic'),
        ),
    ]
