# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20170627_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkchatroom',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
