# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_networkchatroom_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkChatroomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=True)),
                ('fetch', models.BooleanField(default=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_networkchatroomuser_chatroom', to='network.NetworkChatroom')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_networkchatroomuser_frame', to='network.NetworkChatFrame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_networkchatroomuser_user', to='network.NetworkAccount')),
            ],
        ),
    ]
