# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_networkchatroomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkchatroomuser',
            name='allow_join',
            field=models.BooleanField(default=False),
        ),
    ]
