# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20170703_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkchatroom',
            name='chat_frame',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.NetworkChatFrame'),
        ),
    ]
