# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20170704_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkchatroomuser',
            name='allow_chat',
            field=models.BooleanField(default=False),
        ),
    ]
