# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_networkchatroomuser_allow_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkchatroomuser',
            name='allow_chat',
        ),
        migrations.AddField(
            model_name='networkchatroomuser',
            name='time_join',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
