# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=200)),
                ('des', models.TextField(null=True)),
                ('age_begin', models.IntegerField(null=True)),
                ('age_end', models.IntegerField(null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('province_unicode', models.CharField(max_length=100, null=True)),
                ('city_unicode', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
