# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='timezone',
            field=models.IntegerField(default=0),
        ),
    ]
