# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20170103_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='privacy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='time_begin',
            field=models.DateTimeField(null=True),
        ),
    ]
