# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0003_auto_20170103_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_contest_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
