# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
