# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_contestpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestpost',
            old_name='create_date',
            new_name='time',
        ),
    ]
