# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0007_auto_20170108_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('contestpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.ContestPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_contestpostcomment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
