# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0010_contestfollow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestfollow',
            unique_together=set([('contest', 'user')]),
        ),
    ]
