# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20170314_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestpostcomment',
            name='contestpost',
        ),
        migrations.RemoveField(
            model_name='contestpostcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContestPostComment',
        ),
    ]
