# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20170314_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestpost',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_contestpost_contest', to='contest.Contest'),
        ),
    ]
