# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 07:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('des', models.TextField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('province_unicode', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('city_unicode', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('age_begin', models.IntegerField()),
                ('age_end', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('fee_des', models.TextField()),
                ('quantity', models.IntegerField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_event_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
