# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20161226_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_type', models.CharField(max_length=100)),
                ('music_type_unicode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(max_length=100)),
                ('sport_type_unicode', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventsport',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
        migrations.AddField(
            model_name='eventmusic',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
