# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20161226_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmusic',
            name='event',
        ),
        migrations.AddField(
            model_name='eventmusic',
            name='event',
            field=models.ManyToManyField(related_name='event_eventmusic_event', to='event.Event'),
        ),
    ]
