# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20161226_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='des',
            field=models.TextField(),
        ),
    ]
