# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20161226_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsport',
            name='event',
        ),
        migrations.AddField(
            model_name='eventsport',
            name='event',
            field=models.ManyToManyField(related_name='event_eventsport_event', to='event.Event'),
        ),
    ]
