# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20161226_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
