# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20161229_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fee',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
