# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20170101_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipants',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
