# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_eventpost_eventpostcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to=event.models.event_upload_path),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='image',
            field=models.ImageField(null=True, upload_to=event.models.eventpost_image_upload),
        ),
    ]
