# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import trait.models


class Migration(migrations.Migration):

    dependencies = [
        ('trait', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='image',
            field=models.ImageField(null=True, upload_to=trait.models.upload_trait_picture),
        ),
    ]
