# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfriendmodel',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='addfriendmodel',
            name='invite_reason',
        ),
        migrations.AlterUniqueTogether(
            name='addfriendmodel',
            unique_together=set([('inviter', 'receiver')]),
        ),
    ]
