# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 12:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0003_auto_20160904_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfriend',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([('user', 'friend')]),
        ),
    ]
