# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0005_auto_20170407_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendheart',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
