# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0006_friendheart_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfriend',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_addfriend_inviter', to='user.User'),
        ),
        migrations.AlterField(
            model_name='addfriend',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_addfriend_receiver', to='user.User'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_friend_friend', to='user.User'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_friend_user', to='user.User'),
        ),
        migrations.AlterField(
            model_name='friendheart',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_friendheart_friend', to='user.User'),
        ),
        migrations.AlterField(
            model_name='friendheart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_friendheart_user', to='user.User'),
        ),
        migrations.AlterField(
            model_name='friendrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_friendrelationship_user', to='user.User'),
        ),
    ]
