# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 13:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0004_auto_20160908_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('des', models.TextField(null=True)),
                ('time', models.DateTimeField()),
                ('street', models.CharField(max_length=100, null=True)),
                ('age1', models.IntegerField(null=True)),
                ('age2', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.BooleanField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_activity_city', to='page.City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_activity_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
