# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activityparticipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='head',
        ),
        migrations.AddField(
            model_name='activity',
            name='fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='sex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='privacy',
            field=models.IntegerField(default=0),
        ),
    ]
