# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20161205_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='street',
            new_name='address',
        ),
        migrations.AddField(
            model_name='activity',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='timezone',
            field=models.IntegerField(default=0),
        ),
    ]
