# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20161207_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
