# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20161207_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='privacy',
            field=models.CharField(max_length=100),
        ),
    ]
