# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20161209_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysport',
            name='activity',
        ),
        migrations.AddField(
            model_name='activitysport',
            name='activity',
            field=models.ManyToManyField(related_name='activity_activitysport_activity', to='activity.Activity'),
        ),
    ]
