# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-10 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20161209_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
