# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0010_activity_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySpam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('been_spam', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='spam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityspam',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_activityspam_activity', to='activity.Activity'),
        ),
        migrations.AddField(
            model_name='activityspam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_activityspam_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='activityspam',
            unique_together=set([('activity', 'user')]),
        ),
    ]
