# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20161214_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='province_unicode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activitysport',
            name='type_of_sport_unicode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
