# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20161214_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEsport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_sport', models.CharField(max_length=100)),
                ('type_of_sport_unicode', models.CharField(max_length=100)),
                ('activity', models.ManyToManyField(related_name='activity_activityesport_activity', to='activity.Activity')),
            ],
        ),
    ]
