# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_activityesport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityesport',
            old_name='type_of_sport',
            new_name='type_of_esport',
        ),
        migrations.RenameField(
            model_name='activityesport',
            old_name='type_of_sport_unicode',
            new_name='type_of_esport_unicode',
        ),
    ]
