# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-18 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_auto_20161216_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_music', models.CharField(max_length=100)),
                ('type_of_music_unicode', models.CharField(max_length=100)),
                ('activity', models.ManyToManyField(related_name='activity_activitymusic_activity', to='activity.Activity')),
            ],
        ),
    ]
