# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_auto_20170102_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityparticipants',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
