# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0019_activitypost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('activitypost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_activitypostcomment_activitypost', to='activity.ActivityPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_activitypostcomment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
