# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0022_privateactivitypost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateActivityPostFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_privateactivitypostfriend_friend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='privateactivitypost',
            name='privacy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='privateactivitypostfriend',
            name='privateactivitypost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_privateactivitypostfriend_privateactivitypost', to='activity.PrivateActivityPost'),
        ),
    ]
