# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0024_auto_20170115_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypost',
            name='privacy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
