# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0025_activitypost_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitypost',
            name='privacy',
        ),
        migrations.RemoveField(
            model_name='activitypost',
            name='private',
        ),
    ]
