# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0026_auto_20170115_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateactivitypost',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='privateactivitypost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='privateactivitypostfriend',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='privateactivitypostfriend',
            name='privateactivitypost',
        ),
        migrations.DeleteModel(
            name='PrivateActivityPost',
        ),
        migrations.DeleteModel(
            name='PrivateActivityPostFriend',
        ),
    ]
