# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 10:36
from __future__ import unicode_literals

import activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0027_auto_20170115_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(null=True, upload_to=activity.models.activity_upload_path),
        ),
        migrations.AlterField(
            model_name='activitypost',
            name='image',
            field=models.ImageField(null=True, upload_to=activity.models.activitypost_image_upload),
        ),
    ]
