# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_groupinfo_intro'),
        ('activity', '0028_auto_20170221_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_activity_group', to='group.Group'),
        ),
    ]
