# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0048_auto_20170503_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', upload_to='uploads/', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(default=0)),
                ('image_width', models.PositiveIntegerField(default=0)),
                ('has_saved', models.BooleanField()),
                ('image_id', models.CharField(max_length=100)),
                ('image_type', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
