# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20170505_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_height',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_width',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
