# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 05:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import moment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=moment.models.upload_image)),
                ('privacy', models.TextField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moment_moment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
