# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20161013_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='time_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='time_hour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='time_minute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='time_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='time_year',
            field=models.BooleanField(default=False),
        ),
    ]
