# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0004_auto_20161022_0245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantmoreinfo',
            unique_together=set([('person', 'planparticipants', 'plan')]),
        ),
    ]
