# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20161022_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantmoreinfo',
            old_name='owner_accepted',
            new_name='owner_invited',
        ),
        migrations.RenameField(
            model_name='participantmoreinfo',
            old_name='user_accepted',
            new_name='user_invited',
        ),
    ]
