# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20161023_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='timezone',
            field=models.IntegerField(null=True),
        ),
    ]
