# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nationality',
            field=models.CharField(choices=[('vn', 'Viet Nam'), ('us', 'United States of America'), ('uk', 'United Kingdom')], max_length=3),
        ),
    ]
