# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='place_born',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='place_live',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
