# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20160908_1314'),
        ('user', '0004_auto_20160905_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ManyToManyField(related_name='user_searchcity_city', to='page.City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
