# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_searchcity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='nationality',
        ),
    ]
