# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20160908_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='country_search',
        ),
    ]
