# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20160908_1314'),
        ('user', '0008_remove_info_country_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='country_search',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info_country_search', to='page.Country'),
        ),
    ]
