# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_info_country_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='born_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='live_place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
