# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20160915_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityOnPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=15)),
                ('activity_icon', models.CharField(choices=[('Sport', (('1', 'badminton'), ('2', 'surfing')))], max_length=10)),
                ('activity_icon_description', models.CharField(max_length=100)),
                ('is_newest', models.BooleanField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
