# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20160921_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityonpost',
            name='activity_icon',
            field=models.CharField(choices=[('Sport', (('1', 'flaticon active person'), ('2', 'flaticon badminton'), ('3', 'flaticon ride bike'), ('4', 'flaticon climbing'), ('5', 'flaticon go fishing'), ('6', 'flaticon golf'), ('7', 'flaticon horse riding'), ('8', 'flaticon flying a kite'), ('9', 'flaticon canoe'), ('10', 'flaticon swimming'), ('11', 'flaticon camping'), ('12', 'flaticon running'), ('13', 'flaticon skateboard'), ('14', 'flaticon ski-lift'), ('15', 'flaticon surfer'), ('16', 'flaticon walking'))), ('Status', (('100', 'fa rocket'), ('101', 'fa mortar-board'), ('102', 'fa flash'), ('103', 'fa heart'), ('104', 'fa hearo')))], max_length=10, null=True),
        ),
    ]
