# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20160923_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
