# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_info_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
