# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_info_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityonpost',
            old_name='activity_icon',
            new_name='activity_icon_code',
        ),
        migrations.RenameField(
            model_name='activityonpost',
            old_name='activity_icon_description',
            new_name='activity_icon_name',
        ),
    ]
