# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20161031_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityonpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityOnPost',
        ),
    ]
