# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20170104_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoEducationSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('time_begin', models.DateTimeField(null=True)),
                ('time_end', models.DateTimeField(null=True)),
                ('is_graduated', models.BooleanField(default=0)),
                ('privacy', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfoEducationUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=200)),
                ('time_begin', models.DateTimeField(null=True)),
                ('time_end', models.DateTimeField(null=True)),
                ('is_graduated', models.BooleanField(default=0)),
                ('privacy', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InfoWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200, null=True)),
                ('privacy', models.CharField(max_length=50)),
                ('time_begin', models.DateTimeField(null=True)),
                ('time_end', models.DateTimeField(null=True)),
                ('is_working', models.BooleanField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MajorUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='infoeducationuniversity',
            name='major',
            field=models.ManyToManyField(related_name='user_infoeducationuniversity_name', to='user.MajorUniversity'),
        ),
        migrations.AddField(
            model_name='infoeducationuniversity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
