# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 08:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20170104_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infowork',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_infowork_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
