# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20170104_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoeducationschool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_infoeducationschool_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='infoeducationuniversity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_infoeducationuniversity_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
