# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_bornplace_liveplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bornplace',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bornplace',
            name='privacy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
