# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20170105_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='infowork',
            name='work_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='infowork',
            unique_together=set([('user', 'work_id')]),
        ),
    ]
