# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20170106_1227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='infowork',
            unique_together=set([]),
        ),
    ]
