# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20170107_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoeducationschool',
            name='time_begin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='infoeducationschool',
            name='time_end',
            field=models.DateField(null=True),
        ),
    ]
