# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20170108_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoeducationuniversity',
            name='major',
        ),
        migrations.AddField(
            model_name='infoeducationuniversity',
            name='major',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='MajorUniversity',
        ),
    ]
