# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20170108_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoeducationuniversity',
            name='time_begin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='infoeducationuniversity',
            name='time_end',
            field=models.DateField(null=True),
        ),
    ]
