# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_activity_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_event_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
