# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20170111_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
