# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 03:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_auto_20170318_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_keyword', models.CharField(max_length=50)),
                ('has_validate', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_emailvalidation_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
