# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_auto_20170430_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=user.models.user_profilepic_upload),
        ),
    ]
