# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20170430_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='241f22c768d944048cd7fe6e154cfede', editable=False, unique=True),
        ),
    ]
