# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_auto_20170504_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='45b16fc79fcd4bb7b79f5d229ffd85e8', editable=False, unique=True),
        ),
    ]
