# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_auto_20170504_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='9eba64d228534fa5bcd21a9df29618da', editable=False, unique=True),
        ),
    ]
