# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profilename',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
