# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('event', '0012_eventpost_eventpostcomment'),
        ('act', '0003_act_des'),
        ('activity', '0021_auto_20170103_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('status_type', models.CharField(max_length=100)),
                ('privacy', models.CharField(max_length=100, null=True)),
                ('act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='act.Act')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
