# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0002_status_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('been_vote', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusvote',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Status'),
        ),
        migrations.AddField(
            model_name='statusvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_statusvote_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='statusvote',
            unique_together=set([('user', 'status')]),
        ),
    ]
