# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_statuscomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscomment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_statuscomment_status', to='status.Status'),
        ),
    ]
