# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0008_actpostcomment_actposttagfriend'),
        ('status', '0005_auto_20170112_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='actpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='act.ActPost'),
        ),
    ]
