# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('status', '0008_auto_20170115_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='eventspost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventsPost'),
        ),
    ]
