# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_eventpost_eventpostcomment'),
        ('status', '0009_status_eventspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='eventpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.EventPost'),
        ),
    ]
