# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20170314_0813'),
        ('status', '0010_status_eventpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
    ]
