# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20170314_0931'),
        ('status', '0011_status_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='contestpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.ContestPost'),
        ),
    ]
