# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trait', '0001_initial'),
        ('status', '0012_status_contestpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='trait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trait.Trait'),
        ),
    ]
