# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0013_status_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
