# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0014_status_has_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
