# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20170330_0338'),
        ('status', '0015_status_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_status_group', to='group.Group'),
        ),
        migrations.AddField(
            model_name='status',
            name='grouppost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.GroupPost'),
        ),
    ]
