# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0016_auto_20170330_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='timeline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
