# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0017_status_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='percent',
        ),
        migrations.AlterField(
            model_name='status',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_status_activity', to='activity.Activity'),
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_status_user', to='user.User'),
        ),
        migrations.AlterField(
            model_name='statuscomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_statuscomment_user', to='user.User'),
        ),
        migrations.AlterField(
            model_name='statusvote',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_statusvote_status', to='status.Status'),
        ),
        migrations.AlterField(
            model_name='statusvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_statusvote_user', to='user.User'),
        ),
    ]
