# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0022_auto_20170513_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='has_image',
        ),
    ]
