# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0025_statusreaction_reactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreaction',
            name='reactionType',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
