# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0026_auto_20170514_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='use_custom_reaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='use_default_reaction',
            field=models.BooleanField(default=True),
        ),
    ]
