# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0027_auto_20170514_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status_type',
            new_name='verb',
        ),
    ]
