# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0029_auto_20170623_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='who_post',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
