# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0031_auto_20170623_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='status',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='status',
            name='event',
        ),
    ]
