# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0032_auto_20170623_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='group',
        ),
        migrations.AlterField(
            model_name='status',
            name='who_owner',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
