# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0033_auto_20170623_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='share',
            field=models.IntegerField(default=0),
        ),
    ]
