# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='privacy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
