# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0004_auto_20170111_1003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actvote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='actvote',
            name='act',
        ),
        migrations.RemoveField(
            model_name='actvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='act',
            name='vote',
        ),
        migrations.DeleteModel(
            name='ActVote',
        ),
    ]
