# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0005_auto_20170111_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='act_approved',
            field=models.BooleanField(default=False),
        ),
    ]
