# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('act', '0006_act_act_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('des', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('privacy', models.CharField(max_length=100)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='act.Act')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
