# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 07:52
from __future__ import unicode_literals

import act.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0010_auto_20170112_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='image',
            field=models.ImageField(null=True, upload_to=act.models.act_image_upload),
        ),
        migrations.AlterField(
            model_name='actpost',
            name='image',
            field=models.ImageField(null=True, upload_to=act.models.actpost_image_upload),
        ),
    ]
