# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0011_auto_20170314_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='des',
            field=models.TextField(null=True),
        ),
    ]
