# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0012_auto_20170319_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='act_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='act',
            name='will_be_posted',
            field=models.BooleanField(default=False),
        ),
    ]
