# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0013_auto_20170324_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='act',
            old_name='will_be_posted',
            new_name='is_used',
        ),
    ]
