# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0014_status_has_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlustagLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plustag_type', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plustag_plustaglife_status', to='status.Status')),
                ('user_of_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plustag_plustaglife_user_of_status', to=settings.AUTH_USER_MODEL)),
                ('user_send_plus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plustag_plustaglife_user_send_plus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='plustaglife',
            unique_together=set([('user_send_plus', 'status', 'plustag_type')]),
        ),
    ]
