# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 01:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plustag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plustaglife',
            name='user_of_status',
        ),
        migrations.AddField(
            model_name='plustaglife',
            name='user_receive_plus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plustag_plustaglife_user_receive_plus', to=settings.AUTH_USER_MODEL),
        ),
    ]
