# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moment', '0002_auto_20170327_0207'),
        ('status', '0015_status_percent'),
        ('plustag', '0003_auto_20170327_0123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plustaglife',
            unique_together=set([('user_send_plus', 'moment', 'plustag_type'), ('user_send_plus', 'status', 'plustag_type')]),
        ),
    ]
