# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plustag', '0004_auto_20170327_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plustaglife',
            name='user_receive_plus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plustag_plustaglife_user_receive_plus', to='user.User'),
        ),
        migrations.AlterField(
            model_name='plustaglife',
            name='user_send_plus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plustag_plustaglife_user_send_plus', to='user.User'),
        ),
    ]
