# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plustag', '0006_auto_20170514_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plustag',
            name='plustag_name',
            field=models.CharField(max_length=30),
        ),
    ]
