# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0016_auto_20161221_1138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anonymous', '0004_auto_20161219_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityparticipants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityParticipants')),
            ],
        ),
        migrations.CreateModel(
            name='BNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_type', models.CharField(max_length=100)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cnotification',
            name='noti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noti.Notification'),
        ),
        migrations.AddField(
            model_name='cnotification',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Post'),
        ),
        migrations.AddField(
            model_name='bnotification',
            name='noti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noti.Notification'),
        ),
        migrations.AddField(
            model_name='bnotification',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Post'),
        ),
        migrations.AddField(
            model_name='bnotification',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Vote'),
        ),
        migrations.AddField(
            model_name='anotification',
            name='noti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noti.Notification'),
        ),
    ]
