# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20161229_0857'),
        ('noti', '0002_dnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventANotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventparticipants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventParticipants')),
                ('noti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noti.Notification')),
            ],
        ),
    ]
