# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0006_auto_20161231_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
