# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0008_eventnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnotification',
            name='noti',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noti.Notification'),
        ),
    ]
