# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20170102_0053'),
        ('noti', '0012_eventgnotification_eventhnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventINotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('noti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noti.Notification')),
            ],
        ),
    ]
