# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0014_activityanotification_activitybnotification_activitycnotification_activitydnotification_activityenot'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycnotification',
            name='time_send',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activitydnotification',
            name='time_send',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventcnotification',
            name='time_send',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventdnotification',
            name='time_send',
            field=models.DateTimeField(null=True),
        ),
    ]
