# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0005_vote_been_vote'),
        ('noti', '0015_auto_20170102_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousANotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Post')),
                ('noti', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noti.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousBNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Post')),
                ('noti', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noti.Notification')),
            ],
        ),
    ]
