# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0005_vote_been_vote'),
        ('noti', '0018_anonymousanotification_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousbnotification',
            name='vote',
        ),
        migrations.AddField(
            model_name='anonymousbnotification',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anonymous.Comment'),
        ),
    ]
