# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noti', '0021_activityjnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityjnotification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_activityjnotification_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
