# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 01:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_eventpost_eventpostcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noti', '0023_activityknotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventJNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('noti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noti.Notification')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_eventjnotification_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventKNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventpostcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventPostComment')),
                ('noti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noti.Notification')),
            ],
        ),
    ]
