# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0024_eventjnotification_eventknotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventjnotification',
            old_name='activity',
            new_name='event',
        ),
    ]
