# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0008_actpostcomment_actposttagfriend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noti', '0027_statusbnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActANotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='act.ActPost')),
                ('noti', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noti.Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_actanotification_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
