# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0029_auto_20170112_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actanotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='actbnotification',
            name='user',
        ),
    ]
