# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('event', '0012_eventpost_eventpostcomment'),
        ('noti', '0032_postanotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsANotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('eventspost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventsPost')),
                ('noti', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noti.Notification')),
            ],
        ),
    ]
