# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20170314_0931'),
        ('noti', '0033_eventsanotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestANotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('contestpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.ContestPost')),
                ('noti', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noti.Notification')),
            ],
        ),
    ]
