# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0049_auto_20170519_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusbnotification',
            name='noti',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='noti_statusbnotification_noti', to='noti.Notification'),
        ),
    ]
