# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0050_auto_20170519_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusbnotification',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_statusbnotification_status', to='status.Status'),
        ),
    ]
