# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_auto_20170504_0311'),
        ('noti', '0053_auto_20170519_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusbnotification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_statusbnotification_user', to='user.User'),
        ),
    ]
