# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 01:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_userskill_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
