# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playfriend',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
    ]
