# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_auto_20170115_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playfriend',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='playfriend',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='playfriend',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='user',
        ),
        migrations.DeleteModel(
            name='PlayFriend',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
